[build]
  publish = "public"
  functions = "netlify/functions"
  command = "npm install"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/downloads/*"
  [headers.values]
    Cache-Control = "no-store"
